[package]
name = "rws"
version = "0.1.0"
authors = ["Joshua Thayer <jthayer@mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.4.0"
rustfft = "3.0.1"
num = "0.2.1"
ndarray = "0.12.1"
